from django.urls import path 
from django.conf import settings
from django.conf.urls.static import static
from .views import *
urlpatterns = [
    path('branch/',branchs.as_view(), name="branch" ),
    path('staffs/',Staffs.as_view(), name="staffs" ),
    path('userss/<int:id>/', UserDetailView.as_view(), name='user-detail'),
    path('editVehicle/<int:id>/', VehicleEditView.as_view(), name='vehicle edit'),
    path('editRoute/<int:id>/', RouteEditView.as_view(), name='route edit'),
    path('employee-detail/<int:id>/',  EmployeeDetailView.as_view(), name='employee-detail'),
    path('passengers/',usertravel.as_view(), name="passengers" ),
    path('update-location/',UpdateLocationView.as_view(), name="passengers" ),
    path('edit_branch/', BranchsListView.as_view(), name='branch-list'),
    path('driver/',driver.as_view(), name="driver" ),
    path('add_driver/',adddriver.as_view(), name="driver" ),
    path('payments/',payments.as_view(), name="payment" ),
    path('addpayments/',addpayments.as_view(), name="payment" ),
    path('reports/monthly-revenue/', monthly_revenue_report, name='monthly-revenue-report'),
    path('reports/monthly-tax/', monthly_tax_report, name='monthly-revenue-report'),
    path('reports/passenger/', Passengers_report, name='monthly-revenue-report'),
    path('reports/vehicles/pdf/', vehicle_report_pdf, name='vehicle-report-pdf'),
    path('driver_payments/',driver_payments.as_view(), name="payment" ),
    path('routeView/',routes.as_view(), name="route" ),
    path('send_alert/', send_alert, name='send_alert'),
    path('notifications/null/', NotificationNullView.as_view(), name='notification-null'),
    path('notifications/', NotificationListViews.as_view(), name='notification-list'),
    path('notifications/<int:pk>/mark_read/', mark_notification_as_read, name='mark-notification-read'),
    path('notifications/mark_all_read/', mark_all_notifications_read, name='mark-all-read'),
    path('route/<int:pk>',detailRoutes.as_view(), name="detail_route" ),
    path('getUser/<int:phonenumber>',getuser.as_view(), name="get_user" ),
    path('sub_travels/<int:rid>',sub_travels.as_view(), name="sub_travel" ),
    path('user/change-password/', PasswordChangeView.as_view(), name='change-password'),
    path('report/',report.as_view(), name="report" ),
    path('recent/',recent.as_view(), name="recent" ),
    path('users/<int:id>/', UserDeactivateAPIView.as_view(), name='user-deactivate'),
    path('pay/<int:id>/',pay_driver, name='user-deactivate'),
    path('exit-complete/<int:driver>/', ExitSlipListView.as_view(), name='exit-slip-list'),
    # Backward-compatible driver listing (was exit-slips/<driver>/)
    path('exit-slips/<int:driver>/', ExitSlipListCreateView.as_view(), name='exit-slip-by-driver'),
    path('exit-slips/driver/<int:driver>/', ExitSlipListCreateView.as_view(), name='exit-slip-by-driver-alt'),
    # Detail moved to non-conflicting path
    path('exit-slip/<int:pk>/', ExitSlipDetailView.as_view(), name='exit-slip-detail'),
    path('driver_recent/<int:uid>',driver_recent.as_view(), name="recent driver" ),
    path('level/',levels.as_view(), name="level" ),
    path('vehicles/',vehicles.as_view(), name="vehicle" ),
    path('vehicleUser/',vehicleUser.as_view(), name="vehicle" ),
    path('driver_vehicle/<int:did>',driver_vehicle.as_view(), name="vehicle" ),
    path('tickets/',tickets.as_view(), name="buyticket" ),
    path('mytickets/',ticketofuser.as_view(), name="buyticket" ),
    path('ticket/',buyticket.as_view(), name="buyticket" ),
    path('shortticket/',buyshortticket.as_view(), name="buyshortticket" ),
    path("long-bus-details/<int:pk>/", LongBusDetails.as_view()),
    path("queue/<int:pk>/takeoff-time/", QueueTakeoffUpdate.as_view()),
    path(
        "long/<int:bus_id>/vehicles/",
        LongBusVehiclesView.as_view(),
        name="longbus-vehicles"
    ),
    path(
        "queues/<int:queue_id>/time/",
        UpdateQueueTakeoffTimeView.as_view(),
        name="queue-takeoff-time"
    ),
    path(
        "longbusprices/<int:price_id>/",
        UpdateLongBusPriceView.as_view(),
        name="update-longbus-price"
    ),
    path('vehicle/<int:pk>/', vehiclesDetail.as_view(), name="vehicle-detail"),
  path('add_vehicle/<int:bid>',VehicleViewSet.as_view(), name="vehicle add" ),
    path('branchdetail/<int:pk>', branchDetail.as_view(), name="branch" ),
    path("longbusprices-by-bus/<int:bus_id>/", LongBusPricesByBusView.as_view(), name="longbus-prices-by-bus"),

    path('branchdetail/<int:pk>/', branchDetail.as_view(), name="branch-detail-slash" ),
    path('branch/<int:pk>/', branchDetail.as_view(), name="branch-detail-legacy" ),
    path('stafflist/<int:bid>',staffListAD.as_view(), name="staff list admin" ),
    path('addtraveller/',addtraveller.as_view(), name="add traveller" ),
    path('staffdetail/<int:pk>',userDetail.as_view(), name="staff detail admin" ),
    path('subadmin_dashboard/', sub_dashboard.as_view(), name = "subadmin_dashboard"),
    path('ad_notif/<int:id>', ad_notif.as_view(),name = "admin notification"),
    path('messages/', messages_Add.as_view(),name = "admin notification"),
    path('messages/<int:id>', messages.as_view(),name = "admin notification"),
    path('api/messages/mark_read/', MarkMessagesReadView.as_view(), name='mark-messages-read'),
    path('api/messages/mark_conversation_read/<int:sender_id>/', MarkConversationReadView.as_view(), name='mark-conversation-read'),
    path('ad_notifs/<int:pk>', ad_editnotif.as_view(),name = "edit  notification"),
    path('route/', sub_route.as_view(),name = "sub route"),
    path('stationRoute/<int:sid>', station_route.as_view(),name = "station route"),
    path('delete/', delete, name = "delete"),
    path("nid/<int:pn>",phone_number_search.as_view(),name="phone_number search" ),
    path("othercred/",other_cred.as_view(),name="FAN search" ),
    path('nids/<int:fan>',Fan_search.as_view(),name="FAN search" ), 
    path('ntid/<int:tid>',fan_ticket_search.as_view(),name="FAN ticket search" ), 
    path('payment/', payment_form, name='payment_form'),
    path('payment/callback/', payment_callback, name='payment_callback'),
    path('next/', success_page, name='success_page'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('tracked-vehicles/', VehicleLocation.as_view(), name='tracked-vehicles'),
    path('send-otp/', SendOTPView.as_view(), name='otp-create'),
    path('verify-otp/', OTPVerifyView.as_view(), name='otp-verify'),
    path('queue/vehicles/', GetVehiclesInQueueByRoute.as_view(), name='queue-vehicles-by-route'),
    path('queue/status/<int:vehicle_id>/', CheckQueueStatus.as_view(), name='check-queue'),
    path('queue/leave/<int:vehicle_id>', LeaveQueueView.as_view(), name='leave-queue'),
    path('queue/add/', AddToQueueGenericView.as_view(), name='queue-add'),
    path('queue/board/', BoardPassengerView.as_view(), name='board-passenger'),
    path('queue/<int:bid>/',queueRetrieveView.as_view(), name='board-passenger'),    
    path('request-otp/', RequestOTPView.as_view(), name='request_otp'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset_password'),
    path('notifications/<int:user_id>/', UserNotificationsView.as_view(), name='user-notifications'),
    path('branch/<int:pk>/toggle-status/', toggle_branch_status, name='toggle-branch-status'),
    path('fees/', FeeView.as_view(), name='fees'),
    path('long-buses/', LongBusListCreateView.as_view(), name='long-bus-list'),
    path('long-buses/<int:pk>/', LongBusDetail.as_view(), name='long-bus-detail'),
        path('queue/<int:queue_id>/seats/', QueueSeatsView.as_view(), name='queue-seats'),
   path('long-bus-prices/<int:bus_id>/', LongBusPricesByBusView.as_view(), name='long-bus-prices-by-bus'),   # Preferred detail path (no double /api/ prefix once included under /api/)
   path('long-bus-priceschange/<int:pk>/', LongBusPriceDetailView.as_view(), name='long-bus-price-detail'),

]

